// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWlc-fxYeWXzTG3aOApT7IECX6ioPA-DQ',
    appId: '1:357958245521:web:d42c0f2603533eb5eeb330',
    messagingSenderId: '357958245521',
    projectId: 'attendance-management-sy-5f3f1',
    authDomain: 'attendance-management-sy-5f3f1.firebaseapp.com',
    storageBucket: 'attendance-management-sy-5f3f1.appspot.com',
    measurementId: 'G-PG4L4TSM2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQlSQYvP4G3tHG9-GcmYmYai-u1Y4egI',
    appId: '1:357958245521:android:b09ef228c5f62798eeb330',
    messagingSenderId: '357958245521',
    projectId: 'attendance-management-sy-5f3f1',
    storageBucket: 'attendance-management-sy-5f3f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsuSii7VZ5NHlH39Sj6hHaApRIL4vUydU',
    appId: '1:357958245521:ios:f28fc4a35e5a9cdfeeb330',
    messagingSenderId: '357958245521',
    projectId: 'attendance-management-sy-5f3f1',
    storageBucket: 'attendance-management-sy-5f3f1.appspot.com',
    iosBundleId: 'com.example.demo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsuSii7VZ5NHlH39Sj6hHaApRIL4vUydU',
    appId: '1:357958245521:ios:f28fc4a35e5a9cdfeeb330',
    messagingSenderId: '357958245521',
    projectId: 'attendance-management-sy-5f3f1',
    storageBucket: 'attendance-management-sy-5f3f1.appspot.com',
    iosBundleId: 'com.example.demo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWlc-fxYeWXzTG3aOApT7IECX6ioPA-DQ',
    appId: '1:357958245521:web:44f3105514e9b06eeeb330',
    messagingSenderId: '357958245521',
    projectId: 'attendance-management-sy-5f3f1',
    authDomain: 'attendance-management-sy-5f3f1.firebaseapp.com',
    storageBucket: 'attendance-management-sy-5f3f1.appspot.com',
    measurementId: 'G-K9KPHYFQ3W',
  );

}